dataset: cifar100
data_path: ./store/dataset
order:
  - [87, 0, 52, 58, 44, 91, 68, 97, 51, 15, 94, 92, 10, 72, 49, 78, 61, 14, 8, 86, 84, 96, 18, 24, 32, 45, 88, 11, 4, 67, 69, 66, 77, 47, 79, 93, 29, 50, 57, 83, 17, 81, 41, 12, 37, 59, 25, 20, 80, 73, 1, 28, 6, 46, 62, 82, 53, 9, 31, 75, 38, 63, 33, 74, 27, 22, 36, 3, 16, 21, 60, 19, 70, 90, 89, 43, 5, 42, 65, 76, 40, 30, 23, 85, 2, 95, 56, 48, 71, 64, 98, 13, 99, 7, 34, 55, 54, 26, 35, 39]

seed: [1]

initial_increment: 0
increment: 10
#label: cifar100_demo
label: der_test_cifar100_inc10b0_demo


#Model Cfg
model: "incmodel_test"
convnet: 'resnet18'
train_head: 'softmax'
infer_head: 'softmax'
channel: 64
use_bias: False
last_relu: False

#Optimization;Training related
task_max: 10
lr_min: 0.00005
lr: 0.1
weight_decay: 0.0005
dynamic_weight_decay: False
scheduler: 'multistep'
scheduling:
  - 100
  - 120
batch_size: 128
workers: 8
lr_decay: 0.1
optimizer: "sgd"
epochs: 170
resampling: False
warmup: True
warmup_epochs: 10

der: True
use_aux_cls: True
aux_n+1: True
distillation: "none"
temperature: 2

reuse_oldfc: False
weight_normalization: False
val_per_n_epoch: -1 # Validation Per N epoch. -1 means the function is off.
save_ckpt: True
save_mem: True
load_mem: False

#Memory
coreset_strategy: "iCaRL"  # iCaRL, random
mem_size_mode: "uniform_fixed_total_mem" #uniform_fixed_per_cls, uniform_fixed_total_mem
memory_size: 2000 # Max number of storable examplars
fixed_memory_per_cls: 20 # the fixed number of exemplars per cls

initial_training_config:
  lr: 0.1
  weight_decay: 0.0005
  scheduling:
  - 100
  - 120
  lr_decay: 0.1
  optimizer: sgd
  epochs: 170

postprocessor:
  enable: False
  type: 'bic' #'bic', 'wa'
  epochs: 1
  batch_size: 128
  lr: 0.1
  scheduling:
    - 60
    - 90
    - 120
  lr_decay_factor: 0.1
  weight_decay: 0.0005

decouple:
  enable: True
  epochs: 30
  fullset: False
  lr: 0.1
  scheduling:
    - 15
  lr_decay: 0.1
  weight_decay: 0.0005
  temperature: 5.0

