dataset: cifar10
data_path: ./store/dataset
order:
  - [6, 8, 9, 7, 5, 3, 0, 4, 1, 2]

seed: [1]

initial_increment: 0
increment: 5
label: cifar10_demo

model: oracle_dummy
convnet: rebuffi
use_bias: False
last_relu: False
analyse: True

lr: 0.1
weight_decay: 0.0005
dynamic_weight_decay: False
scheduler: 'multistep'
scheduling:
  - 35
  - 50
lr_decay: 0.1
optimizer: sgd
epochs: 80
#epochs: 120
batch_size: 128
keep_memory: True
val_per_n_epoch: -1
random_classes: False
warmup: True
warmup_epochs: 6

# some options for the new method
der: True
use_aux_cls: True
aux_n+1: True
distillation: "none"
temperature: 2

reuse_oldfc: False
weight_normalization: False
loss_type: ce

# the memory options
coreset_strategy: "iCaRL"
mem_size_mode: uniform_fixed_total_mem
memory_size: 2000
fixed_memory_per_cls: 200

initial_training_config:
  lr: 0.1
  weight_decay: 0.0005
  scheduling:
    - 35
    - 50
  lr_decay: 0.1
  optimizer: sgd
  epochs: 80

postprocessor:
  enable: False
  type: 'bic' #'bic', 'wa'
  epochs: 1
  batch_size: 128
  lr: 0.1
  scheduling:
    - 40
    - 60
  lr_decay_factor: 0.1
  weight_decay: 0.0005

decouple:
  enable: True
  epochs: 20
  lr: 0.1
  scheduling:
    - 10
  lr_decay: 0.1
  weight_decay: 0.0005
  temperature: 5.0
  refresh_param: True
  loader_type: balanced



